/**
 * Alicia Server - dedicated server software
 * Copyright (C) 2024 Story Of Alicia
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 **/

#ifndef COMMAND_PROTOCOL_HPP
#define COMMAND_PROTOCOL_HPP

#include <array>
#include <cstdint>
#include <string_view>

namespace server::protocol
{

//! A constant buffer size for message magic.
//! The maximum size of message payload is 4092 bytes.
//! The extra 4 bytes are reserved for message magic.
constexpr uint16_t BufferSize = 4096;

//! When switching between scenes due to user interaction,
//! a client may request blocking until it receives a specific response from the server.
//! Setting this bit prevents the client from resolving the scene lock when
//! the message is received.
constexpr uint16_t ResolveSceneLockBit = 1 << 15;

//! XOR code.
using XorCode = std::array<std::byte, 4>;

//! A constant 4-byte XOR control value,
//! with which message bytes are XORed.
constexpr int32_t XorControl{
  static_cast<int32_t>(0xA20191CB)};

//! XOR rolling key algorithm constant
constexpr int32_t XorMultiplier{0x20080825};

//! Message magic with which all messages are prefixed.
struct MessageMagic
{
  //! An ID of the message.
  uint16_t id{0};
  //! A length of message payload.
  //! Maximum payload length is 4092 bytes.
  uint16_t length{0};
};

//! Decode message magic value.
//!
//! @param value Magic value.
//! @return Decoded message magic.
MessageMagic decode_message_magic(uint32_t value);

//! Encode message magic.
//!
//! @param magic Message magic.
//! @return Encoded message magic value.
uint32_t encode_message_magic(MessageMagic magic);

//! IDs of the commands in the protocol.
enum class Command : uint16_t
{
  AcCmdCLLogin = 0x7,
  AcCmdCLLoginOK = 0x8,
  AcCmdCLLoginCancel = 0x9,
  AcCmdCLRoomList = 0x10,
  AcCmdCLRoomListOK = 0x11,
  AcCmdCLHeartbeat = 0x12,
  AcCmdCLMakeRoom = 0x13,
  AcCmdCLMakeRoomOK = 0x14,
  AcCmdCLMakeRoomCancel = 0x15,
  AcCmdCLEnterRoom = 0x1c,
  AcCmdCLEnterRoomOK = 0x1d,
  AcCmdCLEnterRoomCancel = 0x1e,
  AcCmdCLLeaveRoom = 0x25,
  AcCmdCLLeaveRoomOK = 0x26,
  AcCmdCLEnterChannel = 0x2b,
  AcCmdCLEnterChannelOK = 0x2c,
  AcCmdCLEnterChannelCancel = 0x2d,
  AcCmdCLLeaveChannel = 0x2e,
  AcCmdCLLeaveChannelOK = 0x2f,
  AcCmdCREnterRoom = 0x30,
  AcCmdCREnterRoomNotify = 0x31,
  AcCmdCREnterRoomOK = 0x32,
  AcCmdCREnterRoomCancel = 0x33,
  AcCmdCRLeaveRoom = 0x34,
  AcCmdCRLeaveRoomNotify = 0x35,
  AcCmdCRLeaveRoomOK = 0x36,
  AcCmdLCNotice = 0x39,
  AcCmdRCNPCSpawn = 0x4a,
  AcCmdCRAttackNPC = 0x4b,
  AcCmdCRAttackNPCNotify = 0x4c,
  AcCmdCRNPCAttach = 0x4f,
  AcCmdCRNPCAttachNotify = 0x50,
  AcCmdRCNPCDestroyed = 0x51,
  AcCmdCRChat = 0x52,
  AcCmdCRChatNotify = 0x53,
  AcCmdCRChangeRoomOptions = 0x54,
  AcCmdCRChangeRoomOptionsNotify = 0x55,
  AcCmdCRReadyRace = 0x58,
  AcCmdCRReadyRaceNotify = 0x59,
  AcCmdCRStartRace = 0x5a,
  AcCmdCRStartRaceNotify = 0x5b,
  AcCmdCRStartRaceCancel = 0x5c,
  AcCmdCRChangeMasterNotify = 0x5d,
  AcCmdCRKick = 0x5e,
  AcCmdCRKickNotify = 0x5f,
  AcCmdCRWhisperNotify = 0x61,
  AcCmdCRAttackMonsterNotify = 0x64,
  AcCmdCRRaceResult = 0x69,
  AcCmdCLCreateNicknameNotify = 0x6b,
  AcCmdCLCreateNickname = 0x6c,
  AcCmdCLCreateNicknameCancel = 0x6e,
  AcCmdCRBuyOwnItem = 0x7b,
  AcCmdCRBuyOwnItemOK = 0x7c,
  AcCmdCRBuyOwnItemCancel = 0x7d,
  AcCmdCLShowInventory = 0x7e,
  AcCmdCLShowInventoryOK = 0x7f,
  AcCmdCLShowInventoryCancel = 0x80,
  AcCmdCRWearEquipment = 0x81,
  AcCmdCRWearEquipmentOK = 0x82,
  AcCmdCRWearEquipmentCancel = 0x83,
  AcCmdCRRemoveEquipment = 0x84,
  AcCmdCRRemoveEquipmentOK = 0x85,
  AcCmdCRRemoveEquipmentCancel = 0x86,
  AcCmdCRChangeTeam = 0x8a,
  AcCmdCRChangeTeamOK = 0x8b,
  AcCmdCRChangeTeamCancel = 0x8c,
  AcCmdCRChangeTeamNotify = 0x8d,
  AcCmdCLUpdateUserSettings = 0x90,
  AcCmdCLUpdateUserSettingsOK = 0x91,
  AcCmdCLUpdateUserSettingsCancel = 0x92,
  AcCmdCRRequestItemOK = 0x94,
  AcCmdCLEnterRoomQuick = 0x95,
  AcCmdCLEnterRoomQuickCancel = 0x96,
  AcCmdCRRequestSpur = 0x99,
  AcCmdCRRequestSpurOK = 0x9a,
  AcCmdCRStarPointGet = 0x9b,
  AcCmdCRStarPointGetOK = 0x9c,
  AcCmdCRHeartbeat = 0x9e,
  AcCmdCRUseItemSlotOK = 0xa3,
  AcCmdCRUseItemSlotCancel = 0xa4,
  AcCmdCRUseItemSlotNotify = 0xa5,
  AcCmdRCAddSkillEffect = 0xa6,
  AcCmdRCRemoveSkillEffect = 0xa7,
  AcCmdCRActivateSkillEffect = 0xa8,
  AcCmdCRChangeUserSlotOK = 0xab,
  AcCmdCRChangeUserSlotCancel = 0xac,
  AcCmdCRChangeUserSlotNotify = 0xad,
  AcCmdRCAddMonster = 0xae,
  AcCmdRCBindMonster = 0xaf,
  AcCmdCRStartingRate = 0xb0,
  AcCmdCLGoodsShopList = 0xb2,
  AcCmdCLGoodsShopListOK = 0xb3,
  AcCmdCLGoodsShopListCancel = 0xb4,
  AcCmdCRRequestMagicItem = 0xb5,
  AcCmdCRRequestMagicItemOK = 0xb6,
  AcCmdCRRequestMagicItemNotify = 0xb7,
  AcCmdCRUseMagicItem = 0xb8,
  AcCmdCRUseMagicItemOK = 0xb9,
  AcCmdCRUseMagicItemCancel = 0xba,
  AcCmdCRUseMagicItemNotify = 0xbb,
  AcCmdRCTeamSpurGauge = 0xbc,
  AcCmdRCMobAddMob = 0xbd,
  AcCmdRCMobMove = 0xbe,
  AcCmdRCMobTrace = 0xbf,
  AcCmdRCMobLookAt = 0xc0,
  AcCmdRCMobSetScale = 0xc1,
  AcCmdRCMobSetState = 0xc2,
  AcCmdRCMobSetHP = 0xc3,
  AcCmdRCMobDetachPart = 0xc4,
  AcCmdRCMobSetMoveType = 0xc5,
  AcCmdRCMobDead = 0xc6,
  AcCmdRCMobUseSkillToGround = 0xc7,
  AcCmdRCMobUseSkillToObject = 0xc8,
  AcCmdRCMobSetKey = 0xc9,
  AcCmdRCMobClearKey = 0xca,
  AcCmdRCMobLead = 0xcb,
  AcCmdRCMobSetHPBySkill = 0xcc,
  AcCmdCRTriggerLevelDevice = 0xcd,
  AcCmdRCActivateLevelDevice = 0xce,
  AcCmdRCActivateLevelDeviceTrigger = 0xcf,
  AcCmdRCDeactivateLevelDeviceTrigger = 0xd0,
  AcCmdCRMobSkillToMob = 0xd2,
  AcCmdRCMobPlayerDamaged = 0xd3,
  AcCmdRCMobPlayerSkillDamaged = 0xd4,
  AcCmdRCMobEndGame = 0xd5,
  AcCmdCRMobAttackMobNotify = 0xd6,
  AcCmdCRMobSkillToMobNotify = 0xd7,
  AcCmdCRMobSkillToMobHit = 0xd8,
  AcCmdRCMobPlayerReflectSkill = 0xd9,
  AcCmdRCMobPlayerStatus = 0xda,
  AcCmdRCMobPlayerSetHP = 0xdb,
  AcCmdRCMobSetHPMax = 0xdd,
  AcCmdRCMobStop = 0xde,
  AcCmdRCMobResetPos = 0xdf,
  AcCmdRCMissionEvent = 0xe0,
  AcCmdRCCreateItem = 0xe1,
  AcCmdRCAchievementUpdateNotify = 0xe4,
  AcCmdCLAchievementCompleteList = 0xe5,
  AcCmdCLAchievementCompleteListOK = 0xe6,
  AcCmdCRHurdleClearResult = 0xe7,
  AcCmdCRHurdleClearResultOK = 0xe8,
  AcCmdRCLevelDeviceAction = 0xea,
  AcCmdCLRequestPersonalInfo = 0xeb,
  AcCmdLCPersonalInfo = 0xec,
  AcCmdLCAchievementRewardNotify = 0xee,
  AcCmdRCMobKnockback = 0xf1,
  AcCmdRCMobSetVelocity = 0xf2,
  AcCmdRCCreateObstacle = 0xf3,
  AcCmdRCMobAttachPart = 0xf4,
  AcCmdRCMobRemoveStatus = 0xf5,
  AcCmdRCMobTargetingOn = 0xf6,
  AcCmdRCMobTargetingOff = 0xf7,
  AcCmdRCMobLinkTo = 0xf8,
  AcCmdRCMobUnlink = 0xf9,
  AcCmdRCMobGazeAt = 0xfa,
  AcCmdRCMobPlayerSetMP = 0xfb,
  AcCmdCLEnterRanch = 0xfc,
  AcCmdCLEnterRanchOK = 0xfd,
  AcCmdCLEnterRanchCancel = 0xfe,
  AcCmdCLLeaveRanchOK = 0x100,
  AcCmdCLLeaveRanchCancel = 0x101,
  AcCmdRCMobPlayerDead = 0x105,
  AcCmdLCMissionRecordUpdate = 0x107,
  AcCmdRCMobRun = 0x108,
  AcCmdCLEnterRanchRandomly = 0x109,
  AcCmdRCMobThrust = 0x10c,
  AcCmdCXEnterXRace = 0x10d,
  AcCmdCRMobPlayerReflectSkill = 0x112,
  AcCmdRCMobSetDefaultState = 0x117,
  AcCmdCLFeatureCommand = 0x118,
  AcCmdRCMobMovingAttack = 0x11a,
  AcCmdCRLog = 0x11b,
  AcCmdRCRagePointNotify = 0x11c,
  AcCmdRCAlert = 0x11d,
  AcCmdCXSend = 0x11e,
  AcCmdCXCast = 0x11f,
  AcCmdRCRevengeTargetNotify = 0x120,
  AcCmdCRP2PResult = 0x121,
  AcCmdLCGameguardCheckQuery = 0x122,
  AcCmdLCGameguardEventNotify = 0x124,
  AcCmdCREnterRanch = 0x12b,
  AcCmdCREnterRanchOK = 0x12c,
  AcCmdCREnterRanchCancel = 0x12d,
  AcCmdCREnterRanchNotify = 0x12e,
  AcCmdCRLeaveRanch = 0x12f,
  AcCmdCRLeaveRanchOK = 0x130,
  AcCmdCRLeaveRanchNotify = 0x132,
  AcCmdCRRanchChat = 0x137,
  AcCmdCRRanchChatNotify = 0x138,
  AcCmdCRRanchSnapshot = 0x139,
  AcCmdCRRanchSnapshotNotify = 0x13a,
  AcCmdCREnterBreedingMarket = 0x13f,
  AcCmdCREnterBreedingMarketOK = 0x140,
  AcCmdCREnterBreedingMarketCancel = 0x141,
  AcCmdCRLeaveBreedingMarket = 0x142,
  AcCmdCRSearchStallion = 0x145,
  AcCmdCRSearchStallionOK = 0x146,
  AcCmdCRSearchStallionCancel = 0x147,
  AcCmdCRRegisterStallion = 0x148,
  AcCmdCRRegisterStallionOK = 0x149,
  AcCmdCRRegisterStallionCancel = 0x14a,
  AcCmdCRUnregisterStallion = 0x14b,
  AcCmdCRUnregisterStallionOK = 0x14c,
  AcCmdCRUnregisterStallionCancel = 0x14d,
  AcCmdCRUpdateEquipmentNotify = 0x14e,
  AcCmdCRStatusPointApply = 0x153,
  AcCmdCRStatusPointApplyOK = 0x154,
  AcCmdCRStatusPointApplyCancel = 0x155,
  AcCmdCRTryBreeding = 0x156,
  AcCmdCRTryBreedingOK = 0x157,
  AcCmdCRTryBreedingCancel = 0x158,
  AcCmdCRBreedingAbandon = 0x15f,
  AcCmdCRBreedingAbandonOK = 0x160,
  AcCmdCRBreedingAbandonCancel = 0x161,
  AcCmdCLRequestFestivalResult = 0x165,
  AcCmdCLRequestFestivalResultOK = 0x166,
  AcCmdCLAchievementCompleteOK = 0x168,
  AcCmdCLAchievementCompleteCancel = 0x169,
  AcCmdCRAchievementUpdateProperty = 0x16b,
  AcCmdCRAchievementBookReward = 0x16c,
  AcCmdCRAchievementBookRewardOK = 0x16d,
  AcCmdCRAchievementBookRewardCancel = 0x16e,
  AcCmdCLDisconnectClientsNotify = 0x170,
  AcCmdCLSetIntroduction = 0x171,
  AcCmdRCSetIntroductionNotify = 0x174,
  AcCmdCRSetKeyAchievement = 0x175,
  AcCmdCRSetKeyAchievementOK = 0x176,
  AcCmdCRSetKeyAchievementCancel = 0x177,
  AcCmdCRAwardEnd = 0x17b,
  AcCmdRCAchievementCompleteNotify = 0x17c,
  AcCmdCRRecoverMount = 0x17d,
  AcCmdCRRecoverMountOK = 0x17e,
  AcCmdCRRecoverMountCancel = 0x17f,
  AcCmdRCKickFromRace = 0x185,
  AcCmdCLGetMessengerInfo = 0x186,
  AcCmdCLGetMessengerInfoOK = 0x187,
  AcCmdCLGetMessengerInfoCancel = 0x188,
  AcCmdCLCheckAccountDBAuthOK = 0x193,
  AcCmdCLCheckAccountDBAuthCancel = 0x194,
  AcCmdRCAwardNotify = 0x195,
  AcCmdRCAwardEnd = 0x196,
  AcCmdCRUpdateMountNickname = 0x197,
  AcCmdCRUpdateMountNicknameOK = 0x198,
  AcCmdCRUpdateMountNicknameCancel = 0x199,
  AcCmdCRAwardStart = 0x19d,
  AcCmdCRTriggerEvent = 0x1a4,
  AcCmdRCTriggerActivate = 0x1a5,
  AcCmdCRUpdateBusyState = 0x1a8,
  AcCmdCRUpdateBusyStateNotify = 0x1a9,
  AcCmdCRRanchStuff = 0x1af,
  AcCmdCRRanchStuffOK = 0x1b0,
  AcCmdCRAwardEndNotify = 0x1b5,
  AcCmdCRLoadingComplete = 0x1b6,
  AcCmdCRLoadingCompleteNotify = 0x1b7,
  AcCmdCLCheckWaitingSeqno = 0x1bb,
  AcCmdCLCheckWaitingSeqnoOK = 0x1bc,
  AcCmdCLUpdateSystemContent = 0x1bd,
  AcCmdLCUpdateSystemContent = 0x1c1,
  AcCmdRCRaceResultNotify = 0x1c3,
  AcCmdRCChangeAIOwner = 0x1c7,
  AcCmdCRPerformanceScore = 0x1c8,
  AcCmdCRRanchCmdAction = 0x1c9,
  AcCmdCRRanchCmdActionNotify = 0x1ca,
  AcCmdCRUpdateMountInfo = 0x1cb,
  AcCmdCRUpdateMountInfoOK = 0x1cc,
  AcCmdCRUpdateMountInfoCancel = 0x1cd,
  AcCmdRCUpdateMountAppearanceNotify = 0x1d3,
  AcCmdCRCheckStallionCharge = 0x1d5,
  AcCmdCRCheckStallionChargeOK = 0x1d6,
  AcCmdRCRoomCountdown = 0x1df,
  AcCmdCRUseItem = 0x1e0,
  AcCmdCRUseItemOK = 0x1e1,
  AcCmdCRUseItemCancel = 0x1e2,
  AcCmdRCAddIdleMountInfoNotify = 0x1e6,
  AcCmdRCUpdateMountInfoNotify = 0x1e7,
  AcCmdCRBreedingWishlist = 0x1e8,
  AcCmdCRBreedingWishlistOK = 0x1e9,
  AcCmdCRBreedingWishlistCancel = 0x1ea,
  AcCmdCRBreedingWishlistAdd = 0x1eb,
  AcCmdCRBreedingWishlistAddOK = 0x1ec,
  AcCmdCRBreedingWishlistAddCancel = 0x1ed,
  AcCmdCRBreedingWishlistDel = 0x1ee,
  AcCmdCRBreedingWishlistDelOK = 0x1ef,
  AcCmdCRBreedingWishlistDelCancel = 0x1f0,
  AcCmdCLEnterRoomQuickStop = 0x1f1,
  AcCmdCLEnterRoomQuickStopOK = 0x1f2,
  AcCmdCLEnterRoomQuickStopCancel = 0x1f3,
  AcCmdCRBreedingTakeMoney = 0x1f4,
  AcCmdCRBreedingTakeMoneyOK = 0x1f5,
  AcCmdCRBreedingTakeMoneyCancel = 0x1f6,
  AcCmdRCFestivalMissionReport = 0x1fb,
  AcCmdCLRequestFestivalPrize = 0x1fc,
  AcCmdCLRequestFestivalPrizeOK = 0x1fd,
  AcCmdCLRequestFestivalPrizeCancel = 0x1fe,
  AcCmdLCBreedingNoticeNotify = 0x203,
  AcCmdCLEnterRoomQuickSuccess = 0x204,
  AcCmdCRRevengeAssign = 0x206,
  AcCmdCRRestartRace = 0x207,
  AcCmdCRRaceResultOK = 0x20a,
  AcCmdCRRaceResultCancel = 0x20b,
  AcCmdRCRoomCountdownCancel = 0x20c,
  AcCmdCRRanchStuffStart = 0x20d,
  AcCmdCRRanchStuffEnd = 0x20e,
  AcCmdCRBreedingFailureCard = 0x20f,
  AcCmdCRBreedingFailureCardOK = 0x210,
  AcCmdCRBreedingFailureCardCancel = 0x211,
  AcCmdCRBreedingFailureCardChoose = 0x212,
  AcCmdCRBreedingFailureCardChooseOK = 0x213,
  AcCmdCRBreedingFailureCardChooseCancel = 0x214,
  AcCmdRCResetPos = 0x215,
  AcCmdCRMountGroupForce = 0x219,
  AcCmdCRMountGroupForceOK = 0x21a,
  AcCmdCRMountGroupForceCancel = 0x21b,
  AcCmdCRMountFamilyTree = 0x21d,
  AcCmdCRMountFamilyTreeOK = 0x21e,
  AcCmdCRMountFamilyTreeCancel = 0x21f,
  AcCmdCRChangeMagicTargetOK = 0x22d,
  AcCmdCRChangeMagicTargetCancel = 0x22e,
  AcCmdCRChangeMagicTargetNotify = 0x22f,
  AcCmdRCRemoveMagicTarget = 0x231,
  AcCmdCRStartMagicTarget = 0x232,
  AcCmdRCUpdateGameMoney = 0x234,
  AcCmdLCSkillCardPresetList = 0x235,
  AcCmdCRChangeSkillCardPreset = 0x236,
  AcCmdCRChangeSkillCardPresetID = 0x237,
  AcCmdCRSkillSystemEvent = 0x23a,
  AcCmdRCSkillSystemEvent = 0x241,
  AcCmdRCGuildModeStar = 0x242,
  AcCmdCRMountInjuryPlayEvent = 0x243,
  AcCmdCRAchievementDetail = 0x244,
  AcCmdCRAchievementDetailOK = 0x245,
  AcCmdCRAchievementDetailCancel = 0x246,
  AcCmdRCDebugMessage = 0x24a,
  AcCmdCRMountInjuryHeal = 0x24b,
  AcCmdCRMountInjuryHealOK = 0x24c,
  AcCmdCRMountInjuryHealCancel = 0x24d,
  AcCmdCREmblemList = 0x251,
  AcCmdCREmblemListOK = 0x252,
  AcCmdCREmblemListCancel = 0x253,
  AcCmdCRSetKeyEmblem = 0x254,
  AcCmdCRSetKeyEmblemOK = 0x255,
  AcCmdCRSetKeyEmblemCancel = 0x256,
  AcCmdCRSetKeyEmblemNotify = 0x257,
  AcCmdCRHousingBuild = 0x25b,
  AcCmdCRHousingBuildOK = 0x25c,
  AcCmdCRHousingBuildCancel = 0x25d,
  AcCmdCRHousingBuildNotify = 0x25e,
  AcCmdCRHousingRepair = 0x262,
  AcCmdCRHousingRepairOK = 0x263,
  AcCmdCRHousingRepairCancel = 0x264,
  AcCmdCRHousingRepairNotify = 0x265,
  AcCmdCRUpdateRanchLevelNotify = 0x269,
  AcCmdCLQueryServerTime = 0x26a,
  AcCmdCLQueryServerTimeOK = 0x26b,
  AcCmdCRExpandMountSlot = 0x26c,
  AcCmdCRExpandMountSlotOK = 0x26d,
  AcCmdCRExpandMountSlotCancel = 0x26e,
  AcCmdCLRequestMountInfo = 0x275,
  AcCmdCLRequestMountInfoOK = 0x276,
  AcCmdCRStudyCareSkill = 0x277,
  AcCmdCRStudyCareSkillOK = 0x278,
  AcCmdCRStudyCareSkillCancel = 0x279,
  AcCmdCRResetCareSkill = 0x27d,
  AcCmdCRResetCareSkillOK = 0x27e,
  AcCmdCRResetCareSkillCancel = 0x27f,
  AcCmdCRTriggerizeAct = 0x283,
  AcCmdRCSupplyItemInsert = 0x286,
  AcCmdCROpCmd = 0x28e,
  AcCmdCROpCmdOK = 0x28f,
  AcCmdLCOpKick = 0x292,
  AcCmdLCHackShieldRequest = 0x293,
  AcCmdCLHackShieldResponse = 0x294,
  AcCmdLCHackShieldResult = 0x295,
  AcCmdCRUnregisterStallionEstimateInfo = 0x296,
  AcCmdCRUnregisterStallionEstimateInfoOK = 0x297,
  AcCmdCRUnregisterStallionEstimateInfoCancel = 0x298,
  AcCmdCRRequestStorage = 0x299,
  AcCmdCRRequestStorageOK = 0x29a,
  AcCmdCRRequestStorageCancel = 0x29b,
  AcCmdLCAlertGiftbox = 0x29d,
  AcCmdCRGetItemFromStorage = 0x29e,
  AcCmdCRGetItemFromStorageOK = 0x29f,
  AcCmdCRGetItemFromStorageCancel = 0x2a0,
  AcCmdCRSendGift = 0x2a4,
  AcCmdCRSendGiftOK = 0x2a5,
  AcCmdCRSendGiftCancel = 0x2a6,
  AcCmdCRPurchaseWithdrawal = 0x2aa,
  AcCmdCRPurchaseWithdrawalOK = 0x2ab,
  AcCmdCRPurchaseWithdrawalCancel = 0x2ac,
  AcCmdCRConfirmItem = 0x2ad,
  AcCmdCRConfirmItemOK = 0x2ae,
  AcCmdCRConfirmItemCancel = 0x2af,
  AcCmdLCGoodsShopListData = 0x2b0,
  AcCmdCLInquiryTreecash = 0x2b1,
  AcCmdCLInquiryTreecashOK = 0x2b2,
  AcCmdCLInquiryTreecashCancel = 0x2b3,
  AcCmdCRCheckStorageItem = 0x2b7,
  AcCmdCRConfirmSetItem = 0x2b8,
  AcCmdCRConfirmSetItemOK = 0x2b9,
  AcCmdCRConfirmSetItemCancel = 0x2ba,
  AcCmdCRCreateGuild = 0x2be,
  AcCmdCRCreateGuildOK = 0x2bf,
  AcCmdCRCreateGuildCancel = 0x2c0,
  AcCmdCRWithdrawGuildMember = 0x2c4,
  AcCmdCRWithdrawGuildMemberOK = 0x2c5,
  AcCmdCRWithdrawGuildMemberCancel = 0x2c6,
  AcCmdCRInviteGuildJoin = 0x2cb,
  AcCmdCRInviteGuildJoinCancel = 0x2cc,
  AcCmdLCInviteGuildJoin = 0x2d2,
  AcCmdLCInviteGuildJoinOK = 0x2d3,
  AcCmdLCInviteGuildJoinCancel = 0x2d4,
  AcCmdCRGuildMemberList = 0x2d6,
  AcCmdCRGuildMemberListOK = 0x2d7,
  AcCmdCRGuildMemberListCancel = 0x2d8,
  AcCmdCRUpdateGuildMemberGrade = 0x2dc,
  AcCmdCRUpdateGuildMemberGradeOK = 0x2dd,
  AcCmdCRUpdateGuildMemberGradeCancel = 0x2de,
  AcCmdCRRequestGuildInfo = 0x2e2,
  AcCmdCRRequestGuildInfoOK = 0x2e3,
  AcCmdCRRequestGuildInfoCancel = 0x2e4,
  AcCmdCRModifyGuildEmblem = 0x2e5,
  AcCmdCRModifyGuildEmblemOK = 0x2e6,
  AcCmdCRModifyGuildEmblemCancel = 0x2e7,
  AcCmdRCWithdrawGuildMemberNotify = 0x2ee,
  AcCmdRCUpdateGuildMemberGradeNotify = 0x2f0,
  AcCmdRCAcceptGuildJoinNotify = 0x2f2,
  AcCmdRCModifyGuildEmblemNotify = 0x2f4,
  AcCmdCRRelayCommand = 0x2f5,
  AcCmdCRRelayCommandNotify = 0x2f6,
  AcCmdCRRelay = 0x2f7,
  AcCmdCRRelayNotify = 0x2f8,
  AcCmdCRChangeNickname = 0x2f9,
  AcCmdCRChangeNicknameOK = 0x2fa,
  AcCmdCRChangeNicknameCancel = 0x2fb,
  AcCmdCRPasswordAuth = 0x300,
  AcCmdCRPasswordAuthOK = 0x301,
  AcCmdCRPasswordAuthCancel = 0x302,
  AcCmdCRServerStats = 0x306,
  AcCmdCRServerStatsNotify = 0x307,
  AcCmdClientNotify = 0x309,
  AcCmdRCLeaveRoom = 0x30b,
  AcCmdCLChangeRanchOption = 0x30d,
  AcCmdCLChangeRanchOptionOK = 0x30e,
  AcCmdCLChangeRanchOptionCancel = 0x30f,
  AcCmdRCMagicExpire = 0x313,
  AcCmdLCPTSPremiumInfo = 0x317,
  AcCmdUpdateEnumValueRace793 = 0x319,
  AcCmdUpdateEnumValueRace794 = 0x31a,
  AcCmdUpdateEnumValueRace795 = 0x31b,
  AcCmdUpdateEnumValuePlayer796 = 0x31c,
  AcCmdUpdateEnumValuePlayer797 = 0x31d,
  AcCmdUpdateEnumValuePlayer798 = 0x31e,
  AcCmdUpdateEnumValueRanch799 = 0x31f,
  AcCmdUpdateEnumValueRanch800 = 0x320,
  AcCmdUpdateEnumValueRanch801 = 0x321,
  AcCmdCRMountRentInfo = 0x322,
  AcCmdCRMountRentInfoOK = 0x323,
  AcCmdCRMountRentInfoCancel = 0x324,
  AcCmdCRMountRent = 0x325,
  AcCmdCRMountRentOK = 0x326,
  AcCmdCRMountRentCancel = 0x327,
  AcCmdCRMountRentNotify = 0x32a,
  AcCmdRCMountRentExpire = 0x32b,
  AcCmdCRMountRentReset = 0x32c,
  AcCmdCRMountRentResetOK = 0x32d,
  AcCmdCRMountRentResetCancel = 0x32e,
  AcCmdCRMountRentResetNotify = 0x32f,
  AcCmdLCOpMute = 0x33c,
  AcCmdCRRegisterDailyQuestGroup = 0x33e,
  AcCmdCRRegisterDailyQuestGroupOK = 0x33f,
  AcCmdCRRegisterDailyQuestGroupCancel = 0x340,
  AcCmdCRUpdateDailyQuest = 0x344,
  AcCmdCRUpdateDailyQuestOK = 0x345,
  AcCmdCRUpdateDailyQuestCancel = 0x346,
  AcCmdCRGiveupDailyQuestOK = 0x34b,
  AcCmdCRGiveupDailyQuestCancel = 0x34c,
  AcCmdCRRequestDailyQuestReward = 0x350,
  AcCmdCRRequestDailyQuestRewardOK = 0x351,
  AcCmdCRRequestDailyQuestRewardCancel = 0x352,
  AcCmdCLRequestDailyQuestList = 0x356,
  AcCmdCLRequestDailyQuestListOK = 0x357,
  AcCmdRCUpdateDailyQuestNotify = 0x35c,
  AcCmdRCCompleteDailyQuestNotify = 0x35d,
  AcCmdCRRequestUser = 0x35e,
  AcCmdCRRequestUserOK = 0x35f,
  AcCmdCRRequestUserCancel = 0x360,
  AcCmdRCRequestUser = 0x367,
  AcCmdCRRequestSystemParam = 0x368,
  AcCmdUpdateEnumValue873 = 0x369,
  AcCmdUpdateEnumValue874 = 0x36a,
  AcCmdCRInviteUser = 0x36d,
  AcCmdCRInviteUserOK = 0x36e,
  AcCmdCRInviteUserCancel = 0x36f,
  AcCmdRCUpdateLeagueScoreNotify = 0x372,
  AcCmdRCUpdateLeagueGradeNotify = 0x375,
  AcCmdCLRequestLeagueInfo = 0x376,
  AcCmdCLRequestLeagueInfoOK = 0x377,
  AcCmdCLRequestLeagueInfoCancel = 0x378,
  AcCmdCRRequestLeagueTeamList = 0x37c,
  AcCmdCRRequestLeagueTeamListOK = 0x37d,
  AcCmdCRRequestLeagueTeamListCancel = 0x37e,
  AcCmdCRRequestLeagueReward = 0x382,
  AcCmdCRRequestLeagueRewardOK = 0x383,
  AcCmdCRRequestLeagueRewardCancel = 0x384,
  AcCmdRCRequestLeagueWeeklyInfoNotify = 0x38f,
  AcCmdCRUpdatePet = 0x390,
  AcCmdRCUpdatePet = 0x392,
  AcCmdRCTimeoutCareUser = 0x393,
  AcCmdRCExchangeItem = 0x397,
  AcCmdRCGameCreateClientItem = 0x398,
  AcCmdCRGameCreateClientItem = 0x399,
  AcCmdCRRequestPetBirth = 0x39a,
  AcCmdCRRequestPetBirthOK = 0x39b,
  AcCmdCRRequestPetBirthCancel = 0x39c,
  AcCmdCRRequestPetBirthNotify = 0x39d,
  AcCmdRCObtainEgg = 0x39e,
  AcCmdCRIncubateEgg = 0x39f,
  AcCmdCRIncubateEggOK = 0x3a0,
  AcCmdCRIncubateEggCancel = 0x3a1,
  AcCmdCRIncubateEggNotify = 0x3a2,
  AcCmdCRPetBornResult = 0x3a4,
  AcCmdCRPetBornResultNotify = 0x3a5,
  AcCmdCRBoostIncubateEgg = 0x3a9,
  AcCmdCRBoostIncubateEggOK = 0x3aa,
  AcCmdCRBoostIncubateEggCancel = 0x3ab,
  AcCmdCRBoostIncubateEggNotify = 0x3ac,
  AcCmdCRBoostIncubateEggOther = 0x3ae,
  AcCmdCRBoostIncubateEggOtherOK = 0x3af,
  AcCmdCRBoostIncubateEggOtherCancel = 0x3b0,
  AcCmdCRBoostIncubateEggOtherNotify = 0x3b1,
  AcCmdCRBoostIncubateInfoList = 0x3b3,
  AcCmdCRBoostIncubateInfoListOK = 0x3b6,
  AcCmdCRAcceptBoostIncubateEgg = 0x3b7,
  AcCmdCRAcceptBoostIncubateEggOK = 0x3b8,
  AcCmdCRAcceptBoostIncubateEggCancel = 0x3b9,
  AcCmdCRAcceptBoostIncubateEggNotify = 0x3ba,
  AcCmdCLMakeGuildParty = 0x3bc,
  AcCmdCLGuildPartyList = 0x3c2,
  AcCmdCLGuildPartyListOK = 0x3c3,
  AcCmdCLEnterGuildParty = 0x3c4,
  AcCmdCLEnterGuildPartyOK = 0x3c5,
  AcCmdCLEnterGuildPartyCancel = 0x3c6,
  AcCmdCLEnterGuildPartyNotify = 0x3c7,
  AcCmdCLLeaveGuildParty = 0x3cb,
  AcCmdCLLeaveGuildPartyOK = 0x3cc,
  AcCmdCLLeaveGuildPartyNotify = 0x3cd,
  AcCmdCLStartGuildPartyMatch = 0x3d0,
  AcCmdCLStartGuildPartyMatchOK = 0x3d1,
  AcCmdCLStartGuildPartyMatchCancel = 0x3d2,
  AcCmdCLStopGuildPartyMatch = 0x3d6,
  AcCmdCLStopGuildPartyMatchOK = 0x3d7,
  AcCmdCLStopGuildPartyMatchCancel = 0x3d8,
  AcCmdLCGuildPartyMatchFound = 0x3dd,
  AcCmdCRUserPetInfos = 0x3e2,
  AcCmdCRUserPetInfosOK = 0x3e5,
  AcCmdCRRegisterQuest = 0x3e6,
  AcCmdCRRegisterQuestOK = 0x3e7,
  AcCmdCRRegisterQuestCancel = 0x3e8,
  AcCmdCRGiveupQuest = 0x3ec,
  AcCmdCRGiveupQuestOK = 0x3ed,
  AcCmdCRGiveupQuestCancel = 0x3ee,
  AcCmdCRRequestQuestReward = 0x3f2,
  AcCmdCRRequestQuestRewardOK = 0x3f3,
  AcCmdCRRequestQuestRewardCancel = 0x3f4,
  AcCmdCLRequestQuestList = 0x3f8,
  AcCmdCLRequestQuestListOK = 0x3f9,
  AcCmdRCUpdateQuestNotify = 0x3fe,
  AcCmdRCGuildRaceInfo = 0x404,
  AcCmdRCGuildRaceResult = 0x406,
  AcCmdCRRequestGuildMatchInfo = 0x408,
  AcCmdCRRequestGuildMatchInfoOK = 0x409,
  AcCmdCRRequestGuildMatchInfoCancel = 0x40a,
  AcCmdLCGuildMatchAvailable = 0x40f,
  AcCmdCLChangeGuildPartyOptions = 0x410,
  AcCmdCLChangeGuildPartyOptionsOK = 0x411,
  AcCmdCLChangeGuildPartyOptionsCancel = 0x412,
  AcCmdCLChangeGuildPartyOptionsNotify = 0x413,
  AcCmdCLRequestSpecialEventList = 0x417,
  AcCmdCLRequestSpecialEventListOK = 0x418,
  AcCmdRCUpdateSpecialEventNotify = 0x41c,
  AcCmdCRRequestGuildRankingInfo = 0x41d,
  AcCmdCRRequestGuildRankingInfoOK = 0x41e,
  AcCmdCRRequestGuildRankingInfoCancel = 0x41f,
  AcCmdCRRequestGuildRankingInfoList = 0x420,
  AcCmdCRRequestGuildRankingInfoListOK = 0x421,
  AcCmdCRRequestGuildRankingInfoListCancel = 0x422,
  AcCmdCRMobKnockback = 0x424,
  AcCmdCRMobActivateSkillEffect = 0x425,
  AcCmdCRRequestPCBangGift = 0x427,
  AcCmdCRRequestPCBangGiftOK = 0x428,
  AcCmdCRRequestPCBangGiftCancel = 0x429,
  AcCmdCRCheckPCBangGiftItem = 0x42d,
  AcCmdCRCheckPCBangGiftItemOK = 0x42e,
  AcCmdCRCheckPCBangGiftItemCancel = 0x42f,
  AcCmdRCResetItemWeekly = 0x436,
  AcCmdRCPetEffect = 0x437,
  AcCmdRCUpdatePetCancel = 0x439,
  AcCmdCROpenRandomBox = 0x43a,
  AcCmdCROpenRandomBoxOK = 0x43b,
  AcCmdCROpenRandomBoxCancel = 0x43c,
  AcCmdCRRideMountNotify = 0x449,
  AcCmdCRRideGrazeMountNotify = 0x44b,
  AcCmdCRRequestNpcDressList = 0x44c,
  AcCmdCRRequestNpcDressListOK = 0x44d,
  AcCmdCRRequestNpcDressListCancel = 0x44e,
  AcCmdRCObstacleStatus = 0x452,
  AcCmdCRRanchCmdActionTo = 0x453,
  AcCmdCRRequestUserUid = 0x454,
  AcCmdCRRequestUserUidOK = 0x455,
  AcCmdCRRequestUserUidCancel = 0x456,
  AcCmdCRKickRanch = 0x45a,
  AcCmdCRKickRanchOK = 0x45b,
  AcCmdCRKickRanchCancel = 0x45c,
  AcCmdRCKickRanchNotify = 0x45d,
  AcCmdCRChangeAge = 0x45e,
  AcCmdCRChangeAgeOK = 0x45f,
  AcCmdCRChangeAgeCancel = 0x460,
  AcCmdRCChangeAgeNotify = 0x464,
  AcCmdCRHideAge = 0x465,
  AcCmdCRHideAgeOK = 0x466,
  AcCmdCRHideAgeCancel = 0x467,
  AcCmdRCHideAgeNotify = 0x46b,
  AcCmdCLPCInfoLog = 0x46c,
  AcCmdLCMessengerCommandInvocation = 0xe06,
  AcCmdUserRaceTimer = 0x1024,
  AcCmdUserRaceTimerOK = 0x1025,
  AcCmdUserRaceCountdown = 0x102d,
  AcCmdUserRaceCloseWait = 0x1030,
  AcCmdUserRaceDeleteNotify = 0x1036,
  AcCmdUserRaceFinal = 0x1037,
  //AcCmdUserRaceFinalNotify = 0x1037,
  AcCmdUserRaceUpdatePos = 0x103f,
  AcCmdGameRaceItemSpawn = 0x1045,
  AcCmdGameRaceItemGet = 0x1048,
  AcCmdGameQuestItemSpawn = 0x104b,
  AcCmdGameQuestItemGet = 0x104c,
  AcCmdBrokerTest = 0x108e,
  AcCmdGameRaceClientUDPInfo = 0x109d,
  AcCmdUserRaceP2PResult = 0x109e,
  AcCmdGameRaceP2PResult = 0x109f,
  AcCmdUserRaceActivateEvent = 0x10a0,
  AcCmdUserRaceActivateInteractiveEvent = 0x10a1,
  AcCmdUserRaceDeactivateEvent = 0x10a2,
  AcCmdUserRaceItemGet = 0x10a3,
  Count = 0x10a4,
};

//! Get the name of the command from its ID.
//! @param command ID of the command to retrieve the name for.
//! @returns If command is registered, name of the command.
//!          Otherwise, returns "n/a".
std::string_view GetCommandName(Command command);

} // namespace server

#endif // COMMAND_PROTOCOL_HPP
